enum ActionTypes {
  GET_APOD_BY_PERIOD = 'apod/GET_APOD_BY_PERIOD',
  GET_APOD_BY_PERIOD_SUCCESS = 'apod/GET_APOD_BY_PERIOD_SUCCESS',
  GET_APOD_BY_PERIOD_ERROR = 'apod/GET_APOD_BY_PERIOD_ERROR',

  GET_APOD_BY_DATE = 'apod/GET_APOD_BY_DATE',
  GET_APOD_BY_DATE_SUCCESS = 'apod/GET_APOD_BY_DATE_SUCCESS',
  GET_APOD_BY_DATE_ERROR = 'apod/GET_APOD_BY_DATE_ERROR',

  INITIALIZE_SELECTED_APOD = 'apod/INITIALIZE_SELECTED_APOD',

  GET_APOD_BY_YEAR = 'apod/GET_APOD_BY_YEAR',
  GET_APOD_BY_YEAR_SUCCESS = 'apod/GET_APOD_BY_YEAR_SUCCESS',
  GET_APOD_BY_YEAR_ERROR = 'apod/GET_APOD_BY_YEAR_ERROR',

  SET_YEAR = 'apod/SET_YEAR',
  SET_PAGE = 'apod/SET_PAGE',

  SET_INITIAL_PAGE_BY_YEAR = 'apod/SET_INITIAL_PAGE_BY_YEAR',
}

export default ActionTypes;
