enum ActionTypes {
  // 사실 두 액션이 구분 될 필요가 없음
  // suffix 제거 
  REQUEST_GET_APOD_BY_PERIOD = 'apod/REQUEST_GET_APOD_BY_PERIOD',
  REQUEST_GET_APOD_BY_PERIOD_SUCCESS = 'apod/REQUEST_GET_APOD_BY_PERIOD_SUCCESS',
  REQUEST_GET_APOD_BY_PERIOD_ERROR = 'apod/REQUEST_GET_APOD_BY_PERIOD_ERROR',

  // 어떤 목적의 액션인지 명확하지 않음
  REQUEST_GET_APOD_BY_YEAR = 'apod/REQUEST_GET_APOD_BY_YEAR',
  REQUEST_GET_APOD_BY_YEAR_SUCCESS = 'apod/REQUEST_GET_APOD_BY_YEAR_SUCCESS',
  REQUEST_GET_APOD_BY_YEAR_ERROR = 'apod/REQUEST_GET_APOD_BY_YEAR_ERROR',
}

export default ActionTypes;
